sudo: required
servies:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - openssl aes-256-cbc -K $encrypted_5093eaf3d472_key -iv $encrypted_5093eaf3d472_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project aphrodite-246612
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials aphrodite-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

script:
  - ls

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
