version: '3'
services:
  postgres:
    image: 'postgres:latest'
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
  api:
    image: node:alpine
    working_dir: /app
    command: npm run dev
    volumes: 
      - ./server:/app
    environment: 
      - PORT=5000
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=postgres
      - PG_PASSWORD=psotgres_password
      - PG_PORT=5432
  client:
    image: node:alpine
    working_dir: /app
    command: npm run dev
    ports:
    - '3000:3000'
    volumes: 
    - ./client:/app
