apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: sherondale/aphrodite-client
          ports:
            - containerPort: 3000
          env:
            - name: BASE_URL
              value: https://aphrodite.sherondale.me/api/v1/
