apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: sherondale/aphrodite-server
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: production
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwtsecret
                  key: JWT_SECRET
            - name: JWT_EXPIRES_IN
              value: "1"
            - name: ORIGIN
              value: https://aphrodite.sherondale.me
            - name: PORT
              value: "5000"
            - name: PG_HOST
              value: postgres-cluster-ip-service
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: postgres
            - name: PG_USER
              value: postgres
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
