### Login

POST http://localhost:3050/api/v1/auth/login
Content-Type: application/json

{
  "email": "anotheruser@gmail.com",
  "password": "pdpdpP123"
}


### Logout

GET http://localhost:3050/api/v1/auth/logout
