####Get all styles

GET http://localhost:3050/api/v1/styles


### Get style with ID

GET http://localhost:3050/api/v1/styles/2


### Create a style

POST http://localhost:3050/api/v1/styles
Content-Type: application/json

{
  "name": "Test Style"
}


### Rename a style

PATCH http://localhost:3050/api/v1/styles/4
Content-Type: application/json

{
  "name": "Renamed Test Style"
}

### Delete a style with ID 

DELETE http://localhost:3050/api/v1/styles/4


### Add collections

POST http://localhost:3050/api/v1/styles/2/collections
Content-Type: application/json

{
  "collectionIds": [1, 2]
}


### Get all collections

GET http://localhost:3050/api/v1/styles/2/collections

###Delete a collection

DELETE http://localhost:3050/api/v1/styles/2/collections/2


### Add clothes

POST http://localhost:3050/api/v1/styles/2/clothes
Content-Type: application/json

{
  "clothIds": [1, 2]
}


### Get all clothes

GET http://localhost:3050/api/v1/styles/2/clothes

###Delete a cloth

DELETE http://localhost:3050/api/v1/styles/2/clothes/2

